### ISSUE TITLE
Error while trying to delete old script folder.

### ISSUE THREAD

**Issue by bablosoft** [CheshireCaat/bas-remote-node#5]
**Steps to reproduce:**

1) Create new BAS script and upload it to server.
2) Run it with following code:

```
const scriptClient = new BasRemoteClient({ scriptName: 'YourScriptName' });
await scriptClient.start();
await scriptClient.close();
```
3) Make any change and upload script on server.
4) Run it again with same code.

**Actual result:**

You will get error 

```directory not empty, rmdir 'd:\dev\BASRemoteControl\node\data\run\TestRemoteControl\3afb1'```

**Comment by CheshireCaat** [comment]
I tried to reproduce this problem, everything works fine for me, but I found information that recursive rmdir cannot be used in versions of NodeJS lower than 12. I fix it soon.

**Comment by bablosoft** [comment]
Yes, that is probably because old node version, but please fix anyway.

**Comment by CheshireCaat** [comment]
Please, try a new version

**Comment by bablosoft** [comment]
Thanks, it works.
